### ISSUE TITLE
Create a Design Document for the Salesforce to Oracle EBS story

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#25] opened 2017-06-16 15:49 UTC

**Comment by kahboom** [comment] 2017-06-20 20:52
I think this is a duplicate of #23 ? Could be wrong though.. :joy:

**Comment by chirino** [comment] 2018-03-26 08:47
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (169/150 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-3.smtp.github.com ([192.30.252.194]:59087)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nmk-0013dV-8p
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:22 -0600
Date: Mon, 26 Mar 2018 01:47:11 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054031;
	bh=ZWF9uls/ga7Bu3rdGbVjgjTkVCXwrvFUpd0RhYpeuUY=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=OxBhpdB0XMFil3C5XRWkuTrZjm2YKRcTOeKLIqVjhI6o9W1f7QKdJHdvyAT7K5LB3
	 A2Tz8Obth5Zl41Lk/6tXVJ/RTTL4MqV6v3ThjRBYj9jdBV4PuNOSXpcj2Ecy2dE2cF
	 CQ75yxA5DzESCFFiHP74krDwUFPdHrdA8mn5FOGo=

**Closed as completed** 2018-03-26 08:47 UTC
Labels: Salesforce, Oracle EBS
